// data.jsx — mock report content for the examples gallery.
// Real Tadawul-listed company names used descriptively; metrics are mock/illustrative.

const SERVICES = [
  {
    id: 'earnings',
    num: '01',
    ar: 'مكالمات نتائج الشركات',
    en: 'Earnings Call Reports',
    desc: 'مكالمات نتائج الشركات السعودية المدرجة، تشمل تعليقات الإدارة، أبرز المؤشرات المالية، ورؤى موجَّهة للمستثمرين وتوجيهات الشركة للإيرادات والأرباح والإجابة على أسئلة المحللين.',
    tags: [],
  },
  {
    id: 'brokerage',
    num: '02',
    ar: 'تقارير بيوت الخبرة والأبحاث',
    en: 'Brokerage & Research House Reports',
    desc: 'ملخصات لأبرز تقارير الأبحاث الصادرة عن بيوت الوساطة وبنوك الاستثمار، مع التركيز على السعر المستهدف، التوصية، الفرضيات، ومضاعفات التقييم.',
    tags: [],
  },
  {
    id: 'qualitative',
    num: '03',
    ar: 'تقارير نوعية وتحليلات خاصة',
    en: 'Special Qualitative Reports',
    desc: 'تقارير معمَّقة عن الشركات السعودية المدرجة تتناول نموذج الأعمال، محركات النمو، المنافسة، اتجاهات القطاع، والنظرة المستقبلية.',
    tags: [],
  },
];

const REPORTS = [
  {
    cat: 'earnings',
    co: 'لوسيد',
    ticker: 'LCID',
    title: 'مكالمة عرض النتائج — الربع الأول 2026',
    desc: 'ملخص لأبرز ما ورد في مكالمة لوسيد حول نتائج الربع الأول، مسار التسليمات، السيولة، وتطورات الإنتاج والطلب.',
    date: '2026·05·24',
    cover: 'banners/lucid-q1-2026.png',
    link: 'https://x.com/AlsagriCapital/status/2058509712400748765?s=20',
  },
  {
    cat: 'earnings',
    co: 'الأمار',
    ticker: '6014.SR',
    title: 'مكالمة عرض النتائج — 19 مايو 2026',
    desc: 'قراءة لأبرز النقاط التشغيلية والمالية في مكالمة شركة الأمار، مع متابعة أداء العلامات التجارية وتوسع الفروع.',
    date: '2026·05·19',
    cover: 'banners/alamar-q1-2026.png',
    link: 'https://x.com/AlsagriCapital/status/2056826874970636328?s=20',
  },
  {
    cat: 'earnings',
    co: 'لوبريف',
    ticker: '2223.SR',
    title: 'مكالمة عرض النتائج — 11 مايو 2026',
    desc: 'استعراض لأداء لوبريف في الربع الأول، تطورات الهوامش، الطلب على زيوت الأساس، وأبرز توجيهات الإدارة.',
    date: '2026·05·11',
    cover: 'banners/luberef-q1-2026.png',
    link: 'https://x.com/AlsagriCapital/status/2054278258380673307?s=20',
  },
  // ── Earnings calls ─────────────────────────────────────────────
  {
    cat: 'earnings',
    co: 'أرامكو السعودية',
    ticker: '2222.SR',
    title: 'مكالمة نتائج الربع الأول 2026',
    desc: 'استعراض أبرز ملاحظات الإدارة حول مستويات الإنتاج، التدفقات النقدية الحرة، وسياسة التوزيعات النقدية.',
    date: '2026·05·11',
    cover: 'banners/aramco-q1-2026.png',
    link: 'https://x.com/AlsagriCapital/status/2054657346824249766?s=20',
  },
  {
    cat: 'earnings',
    co: 'أفالون فارما',
    ticker: '4017.SR',
    title: 'مكالمة نتائج الربع الأول 2026',
    desc: 'استعراض نتائج الشركة، نمو خط الإنتاج الدوائي، والتوسع التشغيلي.',
    date: '2026·05·13',
    cover: 'banners/avalon-pharma-q1-2026.png',
    link: 'https://x.com/AlsagriCapital/status/2055553928171868648?s=20',
  },
  {
    cat: 'earnings',
    co: 'المراعي',
    ticker: '2280.SR',
    title: 'مكالمة نتائج الربع الأول 2026',
    desc: 'مناقشة هوامش الربحية، تكاليف الأعلاف، وأداء قطاعَي الألبان والمخبوزات في السوق المحلية والتصدير.',
    date: '2026·05·10',
    cover: 'banners/almarai-q1-2026.png',
    link: 'https://x.com/AlsagriCapital/status/2054465152372646322?s=20',
  },
  {
    cat: 'earnings',
    co: 'وقت اللياقة',
    ticker: '1830.SR',
    title: 'مكالمة نتائج الربع الأول 2026',
    desc: 'استعراض نمو الإيرادات، إضافة الفروع الجديدة، وحركة الاشتراكات والاحتفاظ بالعملاء.',
    date: '2026·04·30',
    cover: 'banners/fitness-time-q1-2026.png',
    link: 'https://x.com/AlsagriCapital/status/2053427767115464956?s=20',
  },
  {
    cat: 'earnings',
    co: 'رسن',
    ticker: '9558.SR',
    title: 'مكالمة نتائج الربع الأول 2026',
    desc: 'نمو محفظة المنتجات الرقمية، توسع قاعدة العملاء، وآفاق قطاع التأمين والتمويل.',
    date: '2026·05·06',
    cover: 'banners/rasan-q1-2026.png',
    link: 'https://x.com/AlsagriCapital/status/2052330335812157755?s=20',
  },
  {
    cat: 'earnings',
    co: 'سال',
    ticker: '4263.SR',
    title: 'مكالمة نتائج الربع الأول 2026',
    desc: 'استعراض نمو أعمال المناولة الجوية والبرية، الاستثمارات الرأسمالية، وحركة التجارة الدولية.',
    date: '2026·05·06',
    cover: 'banners/sal-q1-2026.png',
    link: 'https://x.com/AlsagriCapital/status/2052042595316928522?s=20',
  },
  // ── Brokerage / research ───────────────────────────────────────
  {
    cat: 'brokerage',
    co: 'لجام',
    ticker: '1830.SR',
    title: 'تقرير الأهلي المالية عن لجام',
    desc: 'نموذج من تقارير بيوت الخبرة التي يتم نشرها للمشتركين بالحساب.',
    date: '2026·05',
    cover: 'banners/research-snb-lejam.jpg',
    researchHouse: 'الأهلي المالية',
  },
  {
    cat: 'brokerage',
    co: 'أديس',
    ticker: '2382.SR',
    title: 'تقرير الجزيرة كابيتال عن أديس',
    desc: 'نموذج من تقارير بيوت الخبرة التي يتم نشرها للمشتركين بالحساب.',
    date: '2026·05',
    cover: 'banners/research-aljazira-ades.jpg',
    researchHouse: 'الجزيرة كابيتال',
  },
  {
    cat: 'brokerage',
    co: 'سلوشنز',
    ticker: '7202.SR',
    title: 'تقرير السعودي الفرنسي كابيتال عن سلوشنز',
    desc: 'نموذج من تقارير بيوت الخبرة التي يتم نشرها للمشتركين بالحساب.',
    date: '2026·05',
    cover: 'banners/research-bsf-solutions.jpg',
    researchHouse: 'السعودي الفرنسي كابيتال',
  },
  {
    cat: 'brokerage',
    co: 'أرامكو',
    ticker: '2222.SR',
    title: 'تقرير المتحدة للأوراق المالية عن أرامكو',
    desc: 'نموذج من تقارير بيوت الخبرة التي يتم نشرها للمشتركين بالحساب.',
    date: '2026·05',
    cover: 'banners/research-united-aramco.jpg',
    researchHouse: 'المتحدة للأوراق المالية',
  },
  {
    cat: 'brokerage',
    co: 'لوبريف',
    ticker: '2223.SR',
    title: 'تقرير الإنماء المالية عن لوبريف',
    desc: 'نموذج من تقارير بيوت الخبرة التي يتم نشرها للمشتركين بالحساب.',
    date: '2026·05',
    cover: 'banners/research-alinma-luberef.jpg',
    researchHouse: 'الإنماء المالية',
  },
  {
    cat: 'brokerage',
    co: 'سال',
    ticker: '4263.SR',
    title: 'تقرير الراجحي المالية عن شركة سال',
    desc: 'نموذج من تقارير بيوت الخبرة التي يتم نشرها للمشتركين بالحساب.',
    date: '2025·07',
    cover: 'banners/research-alrajhi-sal.jpg',
    researchHouse: 'الراجحي المالية',
  },
  // ── Qualitative ────────────────────────────────────────────────
  {
    cat: 'qualitative',
    co: 'وقت اللياقة (لجام)',
    ticker: '1830.SR',
    title: 'لجام في 2026: سنة انتقالية تحت اختبار الهوامش والتوسع',
    desc: 'قراءة تربط توصيات بيوت الخبرة مع مكالمة المستثمرين بعد نتائج الربع الأول 2026.',
    date: '2026·05·22',
    cover: 'banners/lejam-2026-transition.png',
    link: 'https://x.com/AlsagriCapital/status/2057801221088424005?s=20',
  },
  {
    cat: 'qualitative',
    co: 'سلوشنز',
    ticker: '7202.SR',
    title: 'تقرير شامل عن سلوشنز: أسباب الهبوط وهل السعر مغري؟',
    desc: 'تحليل لأسباب الهبوط وقراءة جاذبية السعر الحالي في ضوء أساسيات الشركة.',
    date: '2026·02·24',
    cover: 'banners/solutions-special-report.png',
    link: 'https://x.com/AlsagriCapital/status/2026386566118011283?s=20',
  },
  {
    cat: 'qualitative',
    co: 'علم',
    ticker: '7203.SR',
    title: 'شركة علم في 2025: تقرير مالي وأساسي',
    desc: 'تقرير مالي وأساسي يستعرض أداء الشركة ومحركات النمو والعوامل المؤثرة في التقييم.',
    date: '2026·05·19',
    cover: 'banners/elm-2025-financial-fundamental.png',
    link: 'https://x.com/AlsagriCapital/status/2056658937374466556?s=20',
  },
];

const TICKER_STATS = [
  { k: 'REPORTS PUBLISHED',  ar: 'عدد التقارير المنشورة', v: '200', unit: '+' },
  { k: 'COMPANIES COVERED',  ar: 'عدد الشركات المغطاة',  v: '100',  unit: '+' },
];

window.SERVICES = SERVICES;
window.REPORTS = REPORTS;
window.TICKER_STATS = TICKER_STATS;
